few_shots = [
    {'Question': "What is the salary of the HR Manager?",
     'SQLQuery': "SELECT salary FROM Employees WHERE job_title = 'HR Manager';",
     'SQLResult': "Result of the SQL query",
     'Answer': "75000"},

    {'Question': "How many employees have a performance score greater than 85?",
     'SQLQuery': "SELECT COUNT(*) FROM Employees WHERE performance_score > 85;",
     'SQLResult': "Result of the SQL query",
     'Answer': "2"},

    {'Question': "What is the average salary of employees in the IT department?",
     'SQLQuery': "SELECT AVG(salary) FROM Employees WHERE department_id = 2;",
     'SQLResult': "Result of the SQL query",
     'Answer': "65000"},

    {'Question': "What is the total salary of employees in the Marketing department?",
     'SQLQuery': "SELECT SUM(salary) FROM Employees WHERE department_id = 3;",
     'SQLResult': "Result of the SQL query",
     'Answer': "55000"},

    {'Question': "How many employees were hired after January 1, 2019?",
     'SQLQuery': "SELECT COUNT(*) FROM Employees WHERE hire_date > '2019-01-01';",
     'SQLResult': "Result of the SQL query",
     'Answer': "2"},

    {'Question': "What is the highest performance score among all employees?",
     'SQLQuery': "SELECT MAX(performance_score) FROM Employees;",
     'SQLResult': "Result of the SQL query",
     'Answer': "90"},

    {'Question': "How many employees have a salary greater than $70,000?",
     'SQLQuery': "SELECT COUNT(*) FROM Employees WHERE salary > 70000;",
     'SQLResult': "Result of the SQL query",
     'Answer': "2"},

    {'Question': "Which job title has the highest average salary, and what is the average salary?",
     'SQLQuery': """
         SELECT job_title, AVG(salary) AS average_salary
         FROM Employees
         GROUP BY job_title
         ORDER BY average_salary DESC
         LIMIT 1;
     """,
     'SQLResult': "Result of the SQL query",
     'Answer': "HR Manager, 75000"},

    {'Question': "List the top 3 departments with the highest total salary expenditure.",
     'SQLQuery': """
         SELECT department_id, SUM(salary) AS total_salary
         FROM Employees
         GROUP BY department_id
         ORDER BY total_salary DESC
         LIMIT 3;
     """,
     'SQLResult': "Result of the SQL query",
     'Answer': "1, 75000\n2, 65000\n4, 72000"},

    {
        'Question': "Find employees who have a performance score greater than the average performance score of their department.",
        'SQLQuery': """
         SELECT e.first_name, e.last_name, e.performance_score, e.department_id
         FROM Employees e
         JOIN (
             SELECT department_id, AVG(performance_score) AS avg_score
             FROM Employees
             GROUP BY department_id
         ) d ON e.department_id = d.department_id
         WHERE e.performance_score > d.avg_score;
     """,
        'SQLResult': "Result of the SQL query",
        'Answer': "Bob Smith, 90\nCarol Davis, 88"},

    {
        'Question': "What is the total salary paid to employees in each department who have been hired since January 1, 2020?",
        'SQLQuery': """
         SELECT department_id, SUM(salary) AS total_salary
         FROM Employees
         WHERE hire_date >= '2020-01-01'
         GROUP BY department_id;
     """,
        'SQLResult': "Result of the SQL query",
        'Answer': "2, 65000\n3, 55000"},

    {'Question': "Find employees whose salary is above the median salary for their job title.",
     'SQLQuery': """
         SELECT e.first_name, e.last_name, e.salary, e.job_title
         FROM Employees e
         WHERE e.salary > (
             SELECT AVG(salary)
             FROM (
                 SELECT salary
                 FROM Employees
                 WHERE job_title = e.job_title
             ) sub
         );
     """,
     'SQLResult': "Result of the SQL query",
     'Answer': "Carol Davis, 55000"},

    {'Question': "Identify the employees with the highest performance scores in each department.",
     'SQLQuery': """
         SELECT department_id, first_name, last_name, performance_score
         FROM Employees e1
         WHERE performance_score = (
             SELECT MAX(performance_score)
             FROM Employees e2
             WHERE e1.department_id = e2.department_id
         );
     """,
     'SQLResult': "Result of the SQL query",
     'Answer': "Department 1: Alice Johnson, 85\nDepartment 2: Bob Smith, 90"},

    {
        'Question': "Calculate the total revenue generated by employees whose performance score is in the top 10% of all employees.",
        'SQLQuery': """
         SELECT SUM(salary) AS total_revenue
         FROM Employees
         WHERE performance_score >= (
             SELECT PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY performance_score)
             FROM Employees
         );
     """,
        'SQLResult': "Result of the SQL query",
        'Answer': "72000"}
]

